content:
  - name: posts
    label: 文章
    type: collection
    path: _posts
    format: yaml-frontmatter
    filename:
        template: "{year}-{month}-{day}-{primary}.md"
        field: create
    fields:
      - name: title
        label: 标题
        type: string
        required: true

      - name: description
        label: 描述/副标题
        type: string
        required: false

      - name: tags
        label: 标签
        type: string
        list: true

      - name: layout
        label: 布局
        type: string
        default: post
        hidden: true

      - name: body
        label: 正文内容
        type: rich-text
        required: true